In [1]:
print("hello world")


hello world


In [2]:
# machine learning on the diabetes using SVM

In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [5]:
#data collection and the analysis

In [12]:
diabetes_dataset=pd.read_csv('diabetes.csv')

In [13]:
diabetes_dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [14]:
diabetes_dataset.head(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [15]:
#number of rows and column

In [16]:
diabetes_dataset.shape

(768, 9)

In [17]:
#getting the statisical method of the data 

In [19]:
diabetes_dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [20]:
# it says that 25% of value is less the 99,62...

In [22]:
diabetes_dataset["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [23]:
#0 represents the non diabetic people and lebel 1 represent diabeteic

In [25]:
diabetes_dataset.groupby("Outcome").mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [40]:
x=diabetes_dataset.drop(columns="Outcome",axis=1)#if u r droping particular column u have to mention axis=1 else axis=0

In [41]:
y=diabetes_dataset

In [42]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [43]:
y=diabetes_dataset["Outcome"]

In [44]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


In [45]:
#data stadalization

In [46]:
scala=StandardScaler()

In [47]:
scala.fit(x)

StandardScaler()

In [48]:
standardize=scala.transform(x)

In [49]:
#we took all the data and put it into the standard scalar and put it into the common range 

In [50]:
print(standardize)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]


In [51]:
X=standardize

In [52]:
#train test split

In [53]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, stratify=y, random_state=2)

In [54]:
#stratify is basically so that are lebel is devided in both train and test in the same proportion

In [55]:
X_train

array([[-1.14185152, -0.05929342, -3.57259724, ...,  0.05170968,
        -0.9992857 , -0.78628618],
       [ 0.63994726, -0.49745345,  0.04624525, ..., -0.15136112,
        -1.05666795,  0.31985461],
       [-0.84488505,  2.13150675, -0.47073225, ..., -0.24020459,
        -0.2231152 ,  2.19178518],
       ...,
       [ 2.12477957, -1.12339636,  0.25303625, ..., -0.24020459,
        -0.51908683,  0.14967911],
       [ 0.04601433, -0.27837344,  0.45982725, ...,  0.94014439,
        -0.71237443,  0.40494237],
       [-1.14185152, -1.09209922, -0.05715025, ...,  0.48323511,
        -0.70633419, -0.70119842]])

In [56]:
X_train.shape

(614, 8)

In [57]:
X_test.shape

(154, 8)

In [58]:
x_train=pd.DataFrame(X_train)

In [59]:
x_train

0         1         2         3         4         5         6  \
0   -1.141852 -0.059293 -3.572597 -1.288212 -0.692891  0.051710 -0.999286   
1    0.639947 -0.497453  0.046245  0.719086 -0.102454 -0.151361 -1.056668   
2   -0.844885  2.131507 -0.470732  0.154533  6.652839 -0.240205 -0.223115   
3   -0.547919 -0.497453  0.563223  1.534551  0.965543  0.216705  0.722182   
4   -1.141852  1.849832 -0.160546  1.158182 -0.692891  1.270134  4.291962   
..        ...       ...       ...       ...       ...       ...       ...   
609  0.342981 -0.184482  1.493782 -1.288212 -0.692891  2.653554 -0.793918   
610 -0.250952  0.347569  0.563223 -1.288212 -0.692891  0.305548 -0.211035   
611  2.124780 -1.123396  0.253036 -1.288212 -0.692891 -0.240205 -0.519087   
612  0.046014 -0.278373  0.459827  1.220910 -0.692891  0.940144 -0.712374   
613 -1.141852 -1.092099 -0.057150  0.719086 -0.692891  0.483235 -0.706334   

            7  
0   -0.786286  
1    0.319855  
2    2.191785  
3   -0.360847  
4   -0.701198  
..        ...  
609 -0.445935  
610  0.915469  
611  0.149679  
612  0.404942  
613 -0.701198  

[614 rows x 8 columns]

In [60]:
#training the model

In [61]:
classifier= svm.SVC(kernel="linear")

In [62]:
#fitting the training data into the classifier

In [63]:
classifier.fit(X_train,y_train)

SVC(kernel='linear')

In [64]:
#evalution of the model

In [65]:
x_train_accuracy=classifier.predict(X_train)

In [66]:
#this will predict the Outcome of X_train

In [67]:
trainig=accuracy_score(x_train_accuracy,y_train)

In [68]:
trainig

0.7866449511400652

In [69]:
#here we are predicting the data with the original lebel

In [70]:
X_test_predict=classifier.predict(X_test)
training=accuracy_score(X_test_predict,y_test)

In [71]:
training

0.7727272727272727

In [148]:
input_data=(0,105,64,41,142,41.5,0.173,22)

In [149]:
np_array=np.asarray(input_data)

In [150]:
np_array

array([  0.   , 105.   ,  64.   ,  41.   , 142.   ,  41.5  ,   0.173,
        22.   ])

In [151]:
np_array_reshape=np_array.reshape(1,-1)

In [152]:
np_array_reshape

ans=scala.transform(np_array_reshape)
ans

d:\conda\envs\trainy2_O\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.14185152, -0.49745345, -0.26394125,  1.28363829,  0.54008065,
         1.20667481, -0.9026419 , -0.95646168]])

In [153]:
answer=classifier.predict(ans)

In [154]:
answer

array([0], dtype=int64)

In [155]:
print(answer)

[0]


In [156]:
if(answer[0]==0):
    print("not a diabatic patient")
else:
    print("diabatic")

not a diabatic patient
